name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.1.4+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  flutter_bloc: ^8.1.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
